apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-monitor
  labels:
    app: aws-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-monitor
  template:
    metadata:
      labels:
        app: aws-monitor
    spec:
      containers:
      - name: aws-monitor
        image: ackermaster/flask-aws-monitor
        ports:
        - containerPort: 5001
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: "us-east-1"