apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-aws-monitor
  labels:
    app: aws-monitor
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aws-monitor
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: aws-monitor
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: aws-monitor
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: {{ .Values.aws.region | quote }}